[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
optimizer_runs = 100_000
gas_reports = ["Pair", "Penguin", "LpToken"]
fs_permissions = [{ access = "read", path = "./script/rankings/"}]
ffi = true

[profile.default.fuzz]
runs = 1024             # fuzz testing times

[fmt]
line_length = 120       # format line length